# Railway Configuration
# This file tells Railway how to build and deploy your app

[build]
  # Build command - include migrations
  command = "npm run build && npx drizzle-kit migrate --config=drizzle.config.production.ts"
  
  # Force Node.js buildpack
  builder = "NIXPACKS"

[deploy]
  # Start command
  command = "npm start"
  
  # Health check path
  healthcheck = "/api/health"
  
  # Restart policy
  restartPolicy = "always"

[env]
  # Environment variables that Railway should set
  NODE_ENV = "production"