# Railway Configuration
# This file tells Railway how to build and deploy your app

# Railway backend service (Node.js/Express)
[build]
  # Build command - just build, migrations run at startup
  command = "npm install && npm run build"
  
  # Force Node.js buildpack
  builder = "NIXPACKS"

[deploy]
  # Start command
  command = "npm start"
  
  # Health check path
  healthcheck = "/api/health"
  
  # Restart policy
  restartPolicy = "always"

[env]
  # Environment variables that Railway should set
  NODE_ENV = "production"