# Railway Configuration - Full-stack app (Backend + Frontend)
# This file tells Railway how to build and deploy your app

[build]
  # Build frontend first, then backend
  command = "cd client && npm install && npm run build && cd .. && npm install && npm run build"
  
  # Force Node.js buildpack
  builder = "NIXPACKS"

[deploy]
  # Start command
  command = "npm start"
  
  # Health check path
  healthcheck = "/"
  
  # Restart policy
  restartPolicy = "always"

[env]
  # Environment variables that Railway should set
  NODE_ENV = "production"